### ISSUE TITLE
Ejercicio listo para revisión

### ISSUE THREAD

**Issue by JuanMaRuizH** [DevAppWeb/currency-exchange-JuanMaRuizH#1]
Buenas Jorge, el ejercicio está listo para su revisión. Sé que es mejorable, pero he tratado de simplificar la lógica.

Me surge la duda de si utilizar un array multidimensional para los multiplicadores en vez de uno por cada currency. Creo que sería lo más apropiado ya que permitiría escalar mejor la aplicación ¿estoy en lo correcto?

Un saludo.

**Comment by jivanrod** [comment]
Hola Juan Manuel,

 El ejercicio se ve muy bien y  estoy de acuerdo contigo con que sería más adecuado un array bidimensional para guardar el cambio entre dos divisas. Por otro lado la manera más sencilla de resolverlo es utilizando un único array con los cambios con respecto a una de ellas, por ejemplo el Euro:

```php
$cambios = ['EUR' => 1, 'USD' => 1,21, 'YEN' => 137,45, 'GBP' => 0,89]
// Teniendo las divisas almacenadas en $divisa1 y $divisa2 y la cantidad en $cantidad
$cambio = $cantidad * $cambios[$divisa1] / $cambios[$divisa2]
``` 
De esta manera la tarea de añadir más opciones de cambio se reduce a extender la tabla de cambios

Un saludo

**Comment by JuanMaRuizH** [comment]
Buenas Jorge,

El hecho de no utilizar la manera que propones, aunque la contemplé y probé, fue porque el cambio no lo hacía de manera tan exacta como la implementación final. Aunque puede que hiciera los cálculos bien.

Una pregunta acerca de la creación de un array. He visto tanto en la documentación y como en ejemplos que siempre se utiliza `$cambios = array('key1': => value, 'key2' => value)` y tú sin embargo utilizas los corchetes. ¿Qué diferencias existen entre utilizar una y otra forma? ¿Qué tipo de implicación tiene sobre el rendimiento de un programa hacerlo de una manera u otra?.

Gracias.

Un saludo.

**Comment by jivanrod** [comment]
El tema de la notación de los arrays es meramente sintáctico y no me consta que tenga ninguna implicación a nivel de rendimiento. La notación de corchetes se introduce a partir de a versión 5.4 y pienso que es más moderna y similar al uso de arrays en otros lenguajes.

Un saludo

**Comment by JuanMaRuizH** [comment]
Aclarado, muchas gracias.
